#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loksai-deploy
  labels:
    app: loksai-mvn-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: loksai-mvn-app
  template:
    metadata:
      labels:
        app: loksai-mvn-app
    spec:
      containers:
      - name: loksai-mvn-container
        image: loksaieta/loksaidevops:v1.0
        ports:
        - containerPort: 8080
